### ISSUE TITLE
Question about recursiveness

### ISSUE THREAD

**Issue by danielslyman** [Pixep/crowlet#17]
I have a quick question, does it, or can it be implemented to recursively crawl sitemaps/xml files? Or is it only first-level links in the Sitemaps? I'd like to create a Public Sitemap of Sitemaps so I only need to update the container once - if that makes sense.

Thanks!

**Comment by Pixep** [comment]
Hi @danielslyman ! Sorry it seems I didn't receive the notifications from this repository.

If you mean having a top-level sitemap index that references children sitemaps, this is definitely supported, and limited to just one level (as supported by https://github.com/yuya-matsushima/go-sitemap). So you can either point to a sitemap, or a sitemap index that contains sitemaps.

Let me know if that makes sense, and feel free to re-open it otherwise!
